version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - vitalvas
    assignees:
      - vitalvas
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - vitalvas
    assignees:
      - vitalvas
    groups:
      dependencies:
        patterns:
          - '*'
