builds:
  - goos:
      - linux
    goarch:
      - amd64
      - arm64

nfpms:
  - package_name: vxdb
    vendor: The VitalVas
    homepage: https://github.com/vitalvas/vxdb
    maintainer: The VitalVas <source@vitalvas.com>
    description: Simple schema-less Key-Value NoSQL database with simplest API interface
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - dst: /var/lib/vxdb
        type: dir
      - src: scripts/vxdb.service
        dst: /lib/systemd/system/vxdb.service
        file_info:
          mode: 0644

dockers:
  - image_templates:
    - "vitalvas/vxdb:{{ .Tag }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
    - "vitalvas/vxdb:{{ .Tag }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    extra_files:
      - LICENSE
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: vitalvas/vxdb:{{ .Tag }}
    image_templates:
      - vitalvas/vxdb:{{ .Tag }}-amd64
      - vitalvas/vxdb:{{ .Tag }}-arm64
  - name_template: vitalvas/vxdb:latest
    image_templates:
      - vitalvas/vxdb:{{ .Tag }}-amd64
      - vitalvas/vxdb:{{ .Tag }}-arm64
