name: Go Tests

on:
  push:
    paths:
      - '**.go'
      - go.mod
      - go.sum

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6

    - name: Build
      run: go build -v ./...
